name: local_pbr_relighter
description: "A local real-time monocular PBR relighting mobile app using Depth-Anything-V2 and custom GLSL fragment shaders."
version: 1.0.0+5

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  tflite_flutter: ^0.12.1
  image: ^4.8.0
  vector_math: ^2.1.4
  provider: ^6.1.2
  image_picker: ^1.2.2
  path_provider: ^2.1.2
  file_picker: ^8.1.4
  flutter_colorpicker: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/models/depth_anything_v2.tflite
    - assets/models/depth_anything_v3.tflite
    - assets/images/
    - assets/cache/
  shaders:
    - assets/shaders/pbr_relight.frag
